### PR TITLE
make the project structure self-documenting, save shaders outside of …

### PR DESCRIPTION
**Pull request by NathanLovato**
…scenes, separate interface from the dancing godot demo scene.

A practice I adopted recently for educational purposes as viewers and users tend to reproduce what they see in small examples in larger scale projects and get stuck. It doesn't cost much time if you do it from the front and it makes the project self-documenting for any dev with a small amount of experience as it exposes all files and the project's structure.

### CODE REVIEW

**Comment by NathanLovato** [comment]
I didn't touch the shaders but I would not have a parameter to set the sprite's texture nested in the water shader, it's showing a bad practice - better use the texture from the node (working with COLOR, UV) and only add extra ones as needed

**Comment by NathanLovato** [comment]
By the way you already took care of the script and all for a first video, and you said you wanted to cover 3d as well. What would you have me take care of here? I can work on different examples that build upon your work but I need to know what you're going to explain exactly so our work is complementary.

**Comment by BastiaanOlij** [comment]
Cool! UI is not my strong suit so I'll gladly follow your lead.

This was just my input for what I think we should get started with and what I would do if I was to show of the 2D shader options more as something for your to look at and see if that is something you can use, rework, or anything like that. So feel free to use what I've written, or just use the shader examples and turn it into your own thing, or suggest other shaders you would rather do. I figured this would give you something to work with as you mentioned before that shaders aren't your specialty.

Adding the texture as a uniform instead of using TextureRect and Godots build in texture property is a difficult choice. On the one hand I fully agree with you, you're potentially showing someone the wrong approach. On the other hand, I wanted to show how you define a texture input. If we use TextureRect we need to think of a reason to combine a second texture into the shader.

I haven't had time to start working on the 3d part. I wanted us to agree on what we were doing for 2d first so I have a natural thing to progress on. You should do the 2d tutorial, again what I have written so far is just my input and suggestion, you can totally rework it or even throw it overboard and you will not hurt my feelings :)

For the 3d tutorial I would like to start off by referring to your video, telling the person watching that you introduce shaders and that I'm assuming you have watched that. Then mention that we will be doing similar effects in 3d, probably start of with a subdivided plane and build a vertex shader that applies the same sine and cosine function but now to animate the height of each vertex so the plane will start to behave like a wave. 

Then look into doing something fun with the fragment shader. The problem I'm having thinking of something good to show is that it doesn't make sense to texture the water because you'd make the material transparent and have a textured plane underneath. So I'm still thinking about that :)

**Comment by BastiaanOlij** [comment]
I've invited you on this repo btw, so you can merge this when you are ready (didn't want the discussion to disappear into closed just yet)

**Comment by NathanLovato** [comment]
>  I figured this would give you something to work with as you mentioned before that shaders aren't your specialty.

Thank you! I started out doing a bit of tech 3d art years ago, I wrote some shaders back then. But I haven't worked with Godot's tools so I need to dive back into it.

> Adding the texture as a uniform instead of using TextureRect and Godots build in texture property is a difficult choice.

Use the second tex as an offset in a step to remove sin/cos animation and get more flexibility is an option we talked about earlier on. How about that>

>  it doesn't make sense to texture the water because you'd make the material transparent and have a textured plane underneath.

Unless you go for a cartoony art-style:
- https://github.com/TripleEh/StylisedWater_SurfaceShader/
- http://polycount.com/discussion/98578/udk-zelda-water-shader-help

Aside from vertex anim this translates well from 2d to 3d

**Pull request merged**
